# Only run on merge requests, tags, or the main branch
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - check
  - build
  - test

variables:
  GIT_URL: "git@${CI_SERVER_HOST}:"
  GIT_SSH_URL: "ssh://git@${CI_SERVER_HOST}/"
  HTTPS_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/"
  FORCE_COLOR: 1
  TERM: "ansi"

default:
  tags:
    - nix
  before_script:
    - git config --global --add url."$HTTPS_URL".insteadOf "$GIT_URL"
    - git config --global --add url."$HTTPS_URL".insteadOf "$GIT_SSH_URL"

check:
  stage: check
  script:
      - nix-build default.nix --attr checks.pre-commit --no-out-link

build:
  stage: build
  script:
    - nix-build default.nix --attr packages.linchpin --no-out-link
    - nix-build default.nix --attr packages.get_closure --no-out-link

test:
  stage: test
  script:
    - nix-build default.nix --attr checks.tests
