{
 "title": "reproducibility-automation",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "http requests",
   "type": "timeseries",
   "description": "Counting requests (except metrics endpoint) since the last start/restart of the service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "reproducibility_automation_axum_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "waitlist length",
   "type": "timeseries",
   "description": "The number of reports that were received and are not yet fully tested.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "reproducibility_automation_report_waitlist_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pipelines in waitlist",
   "type": "timeseries",
   "description": "The number of different pipeline id's across all reports that are not yet fully tested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "reproducibility_automation_number_of_pipeline_ids",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "comment history",
   "type": "timeseries",
   "description": "The number of locally stored merge comments in case they have to be edited when another report arrives from the same pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "reproducibility_automation_comment_history_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "garbadge collection symlinks",
   "type": "timeseries",
   "description": "The current number of symlinks that are created to protect store derivations from automated garbage collection (should equal the number of reports).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "reproducibility_automation_active_gc_roots",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tokio total park count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "reproducibility_automation_tokio_total_park_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tokio workers count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "reproducibility_automation_tokio_workers_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}